feat(using-dom-events): make functionality for input field which add …
Atlantis-Academy/frontend-study-themetronome pull request #13
Opened 2020-12-11 16:19 UTC by themetronome

…movie item to the list

affects: @lessons/using-dom-events

ISSUES CLOSED: #12

2020-12-11 16:35 UTC, TorinAsakura requested changes

2020-12-11 16:35 UTC, TorinAsakura commented on lessons/using-dom-events/src/index.js
> +      }
почему if {}… if {}… else где?

2020-12-12 09:56 UTC, themetronome commented on lessons/using-dom-events/src/index.js
> +      }
> почему if {}… if {}… else где?

Это дополнительные проверки на длину строки и на наличие чекбокса, внутри проверки `value` инпута. Не уверен что здесь нужен `else`

2020-12-12 12:23 UTC, TorinAsakura commented on lessons/using-dom-events/src/index.js
> +      }
Вопрос в ином, что случится, если не отработает if? Почитай практики.

2020-12-12 14:28 UTC, themetronome commented on lessons/using-dom-events/src/index.js
> +      }
В данном случае, тело условия (любое из них), при значении false - просто не отработает, интерпретатор пойдёт дальше, а именно запишет значение строку `newMovie` без метода `substring()` и/или не выведет в консоль сообщение о том, что "добавлен новый фильм". Тут скорее напрашивается перефразировать вопрос - "Что случится если if отработает?". Возможно разумнее было бы использовать здесь `switch`?

2020-12-16 14:01 UTC, TorinAsakura commented on lessons/using-dom-events/src/index.js
> +      }
В данной конструкции switch будет оверхедом, в целом да, тут нормально, контекст не до конца понятен был

2020-12-16 14:02 UTC, TorinAsakura commented
@themetronome следи за количеством символов в заголовке

2020-12-16 14:02 UTC, TorinAsakura approved these changes

2020-12-16 14:02 UTC, merged