feat(healthy-food-delivery): post xhr from forms
Atlantis-Academy/frontend-study-themetronome pull request #44
Opened 2021-02-04 23:46 UTC by themetronome

affects: @practice/healthy-food-delivery

ISSUES CLOSED: #42

2021-02-05 10:10 UTC, TorinAsakura requested changes

2021-02-05 10:10 UTC, TorinAsakura commented on practice/healthy-food-delivery/package.json
> +  "type": "module",
зачем?

2021-02-05 10:10 UTC, TorinAsakura commented on practice/healthy-food-delivery/src/server.ts
> +const port: number = 8000
Где нарыл?

2021-02-05 10:12 UTC, themetronome commented on practice/healthy-food-delivery/package.json
> +  "type": "module",
Для того, чтобы нода могла использовать es6 модули

2021-02-05 10:15 UTC, themetronome commented on practice/healthy-food-delivery/src/server.ts
> +const port: number = 8000
[Дока](https://nodejs.org/en/docs/guides/getting-started-guide/) и лекции Тимура немного посмотрел

2021-02-05 16:24 UTC, TorinAsakura commented on practice/healthy-food-delivery/package.json
> +  "type": "module",
Да что ты?)) Очень интересно, ааа, получается, без type: module они работать не будут?))

2021-02-05 16:31 UTC, themetronome commented on practice/healthy-food-delivery/package.json
> +  "type": "module",
> Да что ты?)) Очень интересно, ааа, получается, без type: module они работать не будут?))

Если использовать без type: module, тогда нужно использовать .mjs формат

2021-02-10 15:44 UTC, TorinAsakura approved these changes

2021-02-10 15:44 UTC, merged