feat(todo): install CRA & make static components of app
Atlantis-Academy/frontend-study-themetronome pull request #63
Opened 2021-02-24 14:16 UTC by themetronome

affects: @practice/todo

ISSUES CLOSED: #62

2021-03-03 12:33 UTC, TFK70 commented
@themetronome сейчас такая задача:
У вас на данный момент все напоминает кашу, даже несмотря на небольшой объём проекта. Вам нужно привести в порядок те сущности, которые имеются на данный момент. Вынесите используемые компоненты в пакеты, согласно конвенции. Теперь input-form должен быть не просто какой-то папкой с левыми файлами, а сущностью с папкой src и package.json. Еще вам стоит разделить компненты по типу input-form на более мелкие. Создайте отдельно Button, отдельно Input, и соберите из них input-form. И так с каждым компонентом

2021-03-03 12:34 UTC, TFK70 commented on practice/todo/src/components/app/App.tsx
> +      <div className="search-panel d-flex">
И не забыть привести в порядок это место, конечно

2021-03-05 11:33 UTC, themetronome reviewed
По мере разбиения компонентов на пакеты - отвалились бутстраповские стили. Не стал долго завязываться на этом. Буду рад если вы поможете мне @TFK70 @TorinAsakura

2021-03-05 13:19 UTC, TFK70 commented
@themetronome вообще мысль разбиения сложных и простых коспонентов на разные воркспейсы в каком-то месте здравая, но так делать не стоит. Да, input-form состоит из input и button, но на деле это все тот же компонент которому место в ui. Ну и если порассуждать: у вас в проекте есть папка components - значит там компоненты. А что тогда в ui? Те же компоненты. Лучше в ui все и перенесите, а components совсем уберите. И не забывайте про зависимости, все используемые должны быть в package.json и не тянуться из глобального скоупа

2021-03-05 13:52 UTC, TorinAsakura commented
@TFK70 Я в который раз прошу прочитать про работу воркспейсов

2021-03-05 17:32 UTC, TFK70 commented on practice/todo/ui/button/src/Button.tsx
> +export const Button: React.FC<{ className: string }> = ({ children }) => {
@themetronome если внимательно посмотреть вотсюды, можно локализовать + исправить проблему со стилями бутстрапа

2021-03-06 20:36 UTC, TFK70 commented on practice/todo/ui/button/src/Button.tsx
> +export const Button: React.FC<{ className: string }> = ({ children }) => {
@themetronome что-то в последних коммитах стили по-прежнему лежат, ты понял что тут не так?

2021-03-06 20:38 UTC, TFK70 commented on practice/todo/ui/button/src/Button.tsx
> +export const Button: React.FC<{ className: string }> = ({ children }) => {
все, сори, увидел, пульнул криво

2021-03-06 20:50 UTC, TFK70 commented
@themetronome 
1. Что в `ui` делает `app`? Посмотри внимательнее в serenity. `app` - это то, что относится к конкретной странице, это никак не компонент общего назначения
2. Я могу понять что лежит в папке `public` и `ui` не открывая их, но возникают трудности с папкой `src`. Создай из ее содержимого отдельную сущность опираясь на serenity и первый пункт

2021-03-06 22:07 UTC, TorinAsakura commented
@themetronome я что-то до всех пор не пойму, что там за ад вы нагромождаете и почему вы всё ещё не используете actl?

2021-03-06 22:27 UTC, TorinAsakura requested changes

2021-03-06 22:27 UTC, TorinAsakura commented on practice/todo/public/index.html
> +</html>
EOF

2021-03-06 22:27 UTC, TorinAsakura commented on practice/todo/src/index.css
> +body {
Мы не используем CSS

2021-03-06 22:27 UTC, TorinAsakura commented on practice/todo/src/index.tsx
> +ReactDOM.render(
а почему не сделать функцией и вызвать простой render()?

2021-03-06 22:27 UTC, TorinAsakura commented on practice/todo/src/index.tsx
> +  <React.StrictMode>
Зачем?

2021-03-06 22:27 UTC, TorinAsakura commented on .eslintrc.json
>  {
actl lint

2021-03-06 22:27 UTC, TorinAsakura commented on package.json
> +    "lint": "./node_modules/.bin/eslint --fix './**/*.{ts,js,tsx,jsx}'"
actl lint

2021-03-06 22:27 UTC, TorinAsakura commented on package.json
>      "@atlantis-lab/tsconfig": "^0.1.2",
зачем?

2021-03-06 22:27 UTC, TorinAsakura commented on practice/todo/.eslintrc
> +{
actl config eslint

2021-03-06 22:27 UTC, TorinAsakura commented on practice/todo/README.md
> +4. build application - `yarn build`
### Setup
- git clone <…>
- cd <…>
- yarn start
- yarn build

2021-03-06 22:27 UTC, TorinAsakura commented on practice/todo/README.md
> +# Todo
Выглядит как призыв

2021-03-06 22:27 UTC, TorinAsakura commented on practice/todo/config-overrides.ts
> +const path = require('path')
это ещё что за чушь? Зачем ты используешь CJS когда мы используем ESM?

2021-03-06 22:27 UTC, TorinAsakura commented on practice/todo/package.json
> +  },
Зачем тебе транспиляция?

2021-03-06 22:27 UTC, TorinAsakura commented on practice/todo/public/index.html
> +<!DOCTYPE html>
Что тут делает HTML файл и для чего ты закинул в гит папку public?

2021-03-06 22:27 UTC, TorinAsakura commented on practice/todo/src/index.tsx
> +import { App } from '@ui/app'
Что у тебя делает приложение в воркспейсе интерфейсов?

2021-03-06 22:27 UTC, TorinAsakura commented on practice/todo/src/index.tsx
> +import 'bootstrap/dist/css/bootstrap.min.css'
Что тут делает бутстрап?

2021-03-06 22:27 UTC, TorinAsakura commented on practice/todo/src/react-app-env.d.ts
> +/// <reference types="react-scripts" />
боже храни РФ

2021-03-06 22:27 UTC, TorinAsakura commented on practice/todo/tsconfig.json
> +  "extends": "../../tsconfig.json",
круто, тогда за ким хером ты там юзал наш tsconfig?

2021-03-06 22:27 UTC, TorinAsakura commented on practice/todo/ui/app/package.json
> +    "@ui/todo-list": "^0.0.0",
то есть, если я захочу сделать shopping-list мне нужно будет копипастить твой todo-list лишь для того чтобы изменить там пару стилей, так?

2021-03-06 22:27 UTC, TorinAsakura commented on practice/todo/ui/app/package.json
> +    "@ui/input-form": "^0.0.0",
что такое поле-форма?

2021-03-06 22:27 UTC, TorinAsakura commented on practice/todo/ui/app/package.json
> +    "@ui/status-filter": "^0.0.0",
что такое статус-фильтер?

2021-03-06 22:27 UTC, TorinAsakura commented on practice/todo/ui/app/package.json
> +    "@ui/search-field": "^0.0.0",
что такое поиск-поле?

2021-03-06 22:27 UTC, TorinAsakura commented on practice/todo/ui/button/src/Button.tsx
> +    <button className={className} type={type}>
Зачем ты используешь нативные HTML API объекты? Ты же понимаешь, что для того чтобы привести их к нужному виду их надо сбрасывать?

2021-03-06 22:27 UTC, TorinAsakura commented on practice/todo/ui/header/src/Header.tsx
> +      <h1 className="header d-flex">todo</h1>
что такое d-flex?

2021-03-06 22:27 UTC, TorinAsakura commented on practice/todo/ui/input-form/package.json
> +    "@ui/input": "^0.0.0"
То есть, для того чтобы собрать один ui компонент мне нужно тащить за собой ещё два? И в чём же тогда прикол всех наших шаманств с реактом?

2021-03-09 11:50 UTC, merged